name: Calculate sentiment
on: [workflow_dispatch]
jobs:
  sentiment-analysis:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up environment
        run: brew install flight-school/formulae/sentiment jq
      - name: Download archive
        run: curl https://files.pushshift.io/reddit/comments/RC_2005-12.bz2 >> RC_2005-12.bz2
      - name: Select target comments
        env:
            FILTER: '["reddit.com"]'
        run: bzcat RC_2005-12.bz2 | jq --argjson f "$FILTER" -c '. | select(.subreddit | in($f))' >> comments.jsonl
      - name: Calculate sentiments
        run: cat comments.jsonl | ./sentiment_for_lines.sh >> sentiment.txt
      - name: Create dataset
        run: |
          cat comments.jsonl | jq -r '. | [.id, .subreddit, .created_utc] | @tsv' >> basic.tsv
          paste basic.tsv sentiment.txt >> dataset.tsv
      - uses: actions/upload-artifact@v3
        with:
          name: RC_2005-12-sentiment.tsv
          path: dataset.tsv
