name: Calculate sentiment
on: [push]
jobs:
  sentiment-analysis:
    runs-on: self-hosted
    strategy:
      matrix:
        version: [RC_2017-01, RC_2017-02, RC_2017-03, RC_2017-04, RC_2017-05, RC_2017-06, RC_2017-07, RC_2017-08, RC_2017-09, RC_2017-10, RC_2017-11]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up environment
        run: brew install flight-school/formulae/sentiment jq
      - name: Download archive
        run: curl ${{ format('https://files.pushshift.io/reddit/comments/{0}.bz2', matrix.version ) }} >> archive.bz2
      - name: Select target comments
        env:
            FILTER: '["Aave_Official", "binance", "Bitcoin", "cardano", "Chainlink", "cosmosnetwork", "cro", "dogecoin", "eos", "ethereum", "litecoin", "Monero", "nem", "dot", "solana", "Stellar", "Tether", "Tronix", "USDC", "UniSwap", "WBTC", "Ripple"]'
        run: bzcat archive.bz2 | jq --argjson f "$FILTER" -c '. | select(.subreddit == $f[])' >> comments.jsonl
      - name: Calculate sentiments
        run: cat comments.jsonl | ./sentiment_for_lines.sh >> sentiment.txt
      - name: Create dataset
        run: |
          cat comments.jsonl | jq -r '. | [.id, .subreddit, .created_utc] | @tsv' >> basic.tsv
          paste basic.tsv sentiment.txt >> dataset.tsv
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ format('{0}-sentiment.tsv', matrix.version) }}
          path: dataset.tsv
